# Setup
title:               Edward Girling
tagline:             'Data Scientist'
description:         ''
url:                 https://rowlando13.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Edward Girling
  url:               https://twitter.com/Rowlando_13
  email:             noemail@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: UA-146052-15
